
Redshift_datasets:
  target: dev
  outputs:
    dev:
      type: redshift
      host: your_host_url
      port: your_port_number
      dbname: your_database_name
      schema: your_schema_name
      user: your_username
      password: your_password
      region: your_region
      threads: 4
